FROM openjdk:8-jdk-alpine
MAINTAINER anupamgogoi@gmail.com
COPY target/twitter-stats-app-1.0.0.jar /opt/app/twitter-stats-app-1.0.0.jar
ENTRYPOINT ["java","-jar","/opt/app/twitter-stats-app-1.0.0.jar"]
EXPOSE 8081

